### ISSUE TITLE
Report YAML format errors in Bot configuration

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2613]
**Example configuration**

```yaml
collective: BadFormatters
  
  
      tiers: THIS iS Not a Valid YAML!


  @@!!
```

**Actual response**

```
Something went wrong.
```

**Expected Response**

```
YAML file is not properly formatted:
SyntaxError: invalid indentation, got 3 instead of 2
```
