### ISSUE TITLE
Open Collective Bot Sent an "Thank You For Contributing" When a User Was Not Contributing

### ISSUE THREAD

**Issue by zicklag** [opencollective/opencollective#3784]
**Describe the bug**
Open Collective Bot Sent an "Thank You For Contributing" When a User Was Not Contributing

**To Reproduce**
With [this](https://github.com/katharostech/arsenal/blob/master/.github/opencollective.yml#L1-L6) configuration:

```yml
collective: arsenal
tiers:
  - tiers: "*"
    labels: ["backer"]
    message: "Hey <author> , thanks for supporting us on Open Collective! We'll make sure that this issue is reviewed by a team member!"
invitation: false
```

On the https://katharostech/arsenal repository, a user opened an issue ( which has since been converted to a discussion ), and even though we have no contributors on Open Collective the bot gave the following [comment](https://github.com/katharostech/arsenal/discussions/114#discussioncomment-227296):

![image](https://user-images.githubusercontent.com/25393315/102717223-8cd97d00-42a6-11eb-9c87-a5ab2315cd0b.png)

**Expected behavior**
There should have been no comment because the `invitation` is set to `false` and the user is not contributing to our collective.
