### ISSUE TITLE
Read full description link doesn't show any content

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4238]
There's a link here to read more but if I click it nothing happens.

<img width="754" alt="Screen Shot 2021-04-30 at 2 13 01 PM" src="https://user-images.githubusercontent.com/5498878/116640135-3f8cbb00-a9be-11eb-88bf-94dea7e55864.png">

https://opencollective.com/foss-multilingual-computing/expenses/31865

**Comment by Betree** [comment]
There's no more content so in this case, we should not display the `Read full description` link

**Comment by piamancini** [comment]
I see this all the time - it's annoying

**Comment by Betree** [comment]
This wasn't resolved, see https://opencollective.com/grange-villa-mutual-aid/expenses/52270

**Comment by Betree** [comment]
I would love to see a CSS-first solution here that wouldn't rely on sanitizing the content. Something like:

```es6
React.useEffect(() => {
  If (contentRef.clientHeight > 60) {
    setCollapsed(true);
  }
}
```

```css
.collapsed {
  overflow-y: hidden;
  max-height: xxx;
  box-shadow: xxx; /* White gradient at the bottom */
}
```
